### ISSUE TITLE
[Feature]:  Test Methods for Applying Persona Roleplaying Prompts to RAG(Retrieval-Augmented Generation)

### ISSUE THREAD

**Issue by JeongYuH** [lingo-chat/prompt#6]
## Background

> 추가하려는 기능에 대해 간결하게 설명해주세요.
## Details(Todo List)

- [x] RAG(Retrieval-Augmented Generation) 기법을 테스트하고, 제대로 작동하는지 확인하기.
- [x] RAG의 프롬프트를 수정하고, 페르소나를 코드적으로 적용 가능한지 테스트하기
- [x] 만약 테스트 하였을 시, 프롬프트가 제대로 적용되지 않는다면, 어떤식으로 적용해야 사용 가능할지 방안이나 아이디어 생각해보기.

> RAG에 사용되는 문서
- 프롬프트 엔지니어링 기술 서적을 이용하여 작업 진행(prompt repository 내 기술 문서 이용)

**Comment by LewisVille-flow** [comment]
gpt-3.5 api 기반 테스트에서 RAG / 페르소나 각 모듈은 별도로 수행시 정상적으로 작동하지만, 두 작업을 한 번에 동시에 수행하고자 할 경우 RAG, 페르소나 둘 다 모두 오작동하는 경향을 확인하였으며, 이를 위해 각 단계를 별도로 수행하는 agent / 파이프라인을 고안해야할 것으로 판단 중.

**Comment by LewisVille-flow** [comment]
#16 #17 #18 과정을 토대로 Agent flow를 설계하여 해결.
